version: '3.8'

services:
  
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    # https://docs.min.io/minio/baremetal/reference/minio-server/minio-server.html#root-credentials
    # Default user and password are "minioadmin"
    command: server /data --console-address ":9001"
    # volumes:
    #   - ./data:/data
    
