version: '3.8'

services:
  app:
    image: cupcakearmy/morphus
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - minio
    environment:
      ALLOWED_DOMAINS: https://images.unsplash.com https://example.org
      STORAGE: minio
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: morphus
      MINIO_ENDPOINT: http://minio:9000
  
  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data
    volumes:
      - ./data/minio:/data 
