version: '3.8'

services:
  app:
    image: cupcakearmy/morphus
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - minio
    volumes:
      - ./morphus.yaml:/app/morphus.yaml:ro
  
  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data
    volumes:
      - ./data/minio:/data 
